GCC := gcc
CLANG := clang
GLINK := ld
CLINK := ld.lld
CC ?= $(GCC)
LD ?= $(GLINK)
AS := nasm

ASFLAGS := \
	-f \
	elf64

NOPIE_LINK := \
	-no-pie

BUILDDIR := build/
ARCHDIR_X64 := x86_64/
HOSTEDDIR := hosted/
FREESTDIR := freest/
EXEDIR := bin/
LIBDIR := lib/
SRCDIR := src/

.PHONY: genbuild_hosted
genbuild_hosted:
	mkdir -p $(BUILDDIR) \
		$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64) \
		$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(EXEDIR) \
		$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(LIBDIR)

.PHONY: genbuild_freest
genbuild_freest:
	mkdir -p $(BUILDDIR) \
		$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64) \
		$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(EXEDIR) \
		$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(LIBDIR)

$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(LIBDIR)p1.o: $(SRCDIR)$(HOSTEDDIR)$(ARCHDIR_X64)p1.asm | genbuild_hosted
	$(AS) $(ASFLAGS) $^ -o $@

$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(LIBDIR)p1.o: $(SRCDIR)$(FREESTDIR)$(ARCHDIR_X64)p1.asm | genbuild_freest
	$(AS) $(ASFLAGS) $^ -o $@

$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(EXEDIR)p1: $(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(LIBDIR)p1.o
	$(CC) $(NOPIE_LINK) $^ -o $@

$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(EXEDIR)p1: $(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(LIBDIR)p1.o
	$(LD) $(NOPIE_LINK) $^ -o $@

.PHONY: p1h p1f rhp1 rfp1
p1h: $(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(EXEDIR)p1
p1f: $(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(EXEDIR)p1
rhp1:
	$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(EXEDIR)p1
rfp1:
	$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(EXEDIR)p1

.PHONY: clean
clean:
	rm -rf $(BUILDDIR)
	find . -name "*.o" -delete
