GCC := gcc
CLANG := clang
GLINK := ld
CLINK := ld.lld
CC ?= $(GCC)
LD ?= $(GLINK)
AS := nasm

ASFLAGS := \
	-f \
	elf64

NOPIE_LINK := \
	-no-pie

BUILDDIR := build/
ARCHDIR_X64 := x86_64/
HOSTEDDIR := hosted/
FREESTDIR := freest/
EXEDIR := bin/
LIBDIR := lib/
SRCDIR := src/

genbuild_hosted:
	mkdir -p $(BUILDDIR) \
		$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64) \
		$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(EXEDIR) \
		$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(LIBDIR)

genbuild_freest:
	mkdir -p $(BUILDDIR) \
		$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64) \
		$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(EXEDIR) \
		$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(LIBDIR)

$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(LIBDIR)%.o: $(SRCDIR)$(HOSTEDDIR)$(ARCHDIR_X64)%.asm | genbuild_hosted
	$(AS) $(ASFLAGS) $^ -o $@

$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(LIBDIR)%.o: $(SRCDIR)$(FREESTDIR)$(ARCHDIR_X64)%.asm | genbuild_freest
	$(AS) $(ASFLAGS) $^ -o $@

$(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(EXEDIR)%: $(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(LIBDIR)%.o
	$(CC) $(NOPIE_LINK) $^ -o $@

$(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(EXEDIR)%: $(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(LIBDIR)%.o
	$(LD) $(NOPIE_LINK) $^ -o $@

HOSTED_NAMES := $(basename $(notdir $(wildcard $(SRCDIR)$(HOSTEDDIR)$(ARCHDIR_X64)*.asm)))
FREEST_NAMES := $(basename $(notdir $(wildcard $(SRCDIR)$(FREESTDIR)$(ARCHDIR_X64)*.asm)))

HOSTED_BUILD_TARGETS := $(addsuffix h,$(HOSTED_NAMES))
HOSTED_RUN_TARGETS   := $(addprefix rh,$(HOSTED_NAMES))

FREEST_BUILD_TARGETS := $(addsuffix f,$(FREEST_NAMES))
FREEST_RUN_TARGETS   := $(addprefix rf,$(FREEST_NAMES))

.PHONY: $(HOSTED_BUILD_TARGETS) $(HOSTED_RUN_TARGETS)
.PHONY: $(FREEST_BUILD_TARGETS) $(FREEST_RUN_TARGETS)

$(HOSTED_BUILD_TARGETS): %h: $(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(EXEDIR)%
	
$(HOSTED_RUN_TARGETS): rh%: $(BUILDDIR)$(HOSTEDDIR)$(ARCHDIR_X64)$(EXEDIR)%
	$<

$(FREEST_BUILD_TARGETS): %f: $(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(EXEDIR)%

$(FREEST_RUN_TARGETS): rf%: $(BUILDDIR)$(FREESTDIR)$(ARCHDIR_X64)$(EXEDIR)%
	$<

.SECONDARY:

.PHONY: clean
clean:
	rm -rf $(BUILDDIR)
	find . -name "*.o" -delete
